// these are the 3d models that represent the menu items
// add new ones by including a gltf in ./public
// and then adding an object to this array
const models = [
  {
    name: "isaac",
    relativeScale: 40,
    relativeOffsetY: 0,
    text: "dance with me",
    hash: "-MwPIRp8tK0",
    row: 0,
    column: 0,
  },
  {
    name: "strongbad",
    relativeScale: 150,
    relativeOffsetY: 0,
    text: "birthday",
    hash: "1H5T4XF3Wis",
    row: 0,
    column: 1,
  },
  {
    name: "katamari",
    relativeScale: 25,
    relativeOffsetY: 100,
    text: "transparent girl",
    hash: "xbrkV1KaQwc",
    row: 0,
    column: 2,
  },
  {
    name: "daxter",
    relativeScale: 4.5,
    relativeOffsetY: 0,
    text: "kaisle",
    row: 0,
    column: 3,
  },
  {
    name: "rubikscube",
    relativeScale: 500,
    relativeOffsetY: 0,
    text: "rubik",
    row: 1,
    column: 0,
  },
  {
    name: "coke",
    relativeScale: 50,
    relativeOffsetY: -100,
    text: "coke",
    row: 1,
    column: 1,
  },
  {
    name: "fujifilm",
    relativeScale: 200,
    relativeOffsetY: -50,
    text: "fujifilm",
    row: 1,
    column: 2,
  },
  {
    name: "walkman",
    relativeScale: 500,
    relativeOffsetY: 0,
    text: "walkman",
    row: 1,
    column: 3,
  },
  {
    name: "steamdeck",
    relativeScale: 20,
    relativeOffsetY: 0,
    text: "steamdeck",
    row: 2,
    column: 0,
  },
  {
    name: "gshock",
    relativeScale: 15,
    relativeOffsetY: 0,
    text: "gshock",
    row: 2,
    column: 1,
  },
  {
    name: "gundam",
    relativeScale: 25,
    relativeOffsetY: -100,
    text: "gundam",
    row: 2,
    column: 2,
  },
  {
    name: "thinkpad",
    relativeScale: 0.5,
    relativeOffsetY: -100,
    text: "thinkpad",
    row: 2,
    column: 3,
  },
];

export default models;
